networks:
  app-tier:
    driver: bridge


services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - app-tier

  api-gateway:
    image: api-gateway:multistage
    networks:
      - app-tier
    ports:
      - "3000:3000"

  app-user:
    image: app-user:multistage
    depends_on:
      - etcd
    ports:
      - "5051:5051"
  user-db:
    image: postgres
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=user
    volumes:
      - pgdata:/var/lib/postgresql/data

  app-docker:
    image: app-docker:multistage
    depends_on:
      - etcd
    ports:
      - "5052:5052"
  docker-db:
    image: postgres
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
