x-variables:
  common_settings: &common_settings
    image: quay.io/coreos/etcd:v3.5.16
    entrypoint: /usr/local/bin/etcd
    ports:
      - 2379


services:
  api-gateway:
    image: api-gateway:multistage
    ports:
      - "3000:3000"

  app-user:
    image: app-user:multistage
    depends_on:
      - etcd
    ports:
      - "5051:5051"
  user-db:
    image: postgres
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=user
    volumes:
      - pgdata:/var/lib/postgresql/data

  app-docker:
    image: app-docker:multistage
    depends_on:
      - etcd
    ports:
      - "5052:5052"
  docker-db:
    image: postgres
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/var/lib/postgresql/data

  etcd:
    <<: *common_settings
    ports:
      - "2379:2379"
    command:
      - '--name=etcd'
      - '--initial-advertise-peer-urls=http://etcd:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd=http://etcd:2380'
      - '--initial-cluster-state=new'
    volumes:
      - etcd:/etcd_data

volumes:
  pgdata:
  etcd: