// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: pkg/proto/docker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainersRequest) Reset() {
	*x = GetContainersRequest{}
	mi := &file_pkg_proto_docker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainersRequest) ProtoMessage() {}

func (x *GetContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainersRequest.ProtoReflect.Descriptor instead.
func (*GetContainersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{0}
}

func (x *GetContainersRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainersResponse) Reset() {
	*x = GetContainersResponse{}
	mi := &file_pkg_proto_docker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainersResponse) ProtoMessage() {}

func (x *GetContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainersResponse.ProtoReflect.Descriptor instead.
func (*GetContainersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{1}
}

func (x *GetContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type CreateContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_pkg_proto_docker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{2}
}

func (x *CreateContainerRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateContainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_pkg_proto_docker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{3}
}

func (x *CreateContainerResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type StopContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerRequest) Reset() {
	*x = StopContainerRequest{}
	mi := &file_pkg_proto_docker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerRequest) ProtoMessage() {}

func (x *StopContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerRequest.ProtoReflect.Descriptor instead.
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{4}
}

func (x *StopContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StopContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerResponse) Reset() {
	*x = StopContainerResponse{}
	mi := &file_pkg_proto_docker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerResponse) ProtoMessage() {}

func (x *StopContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerResponse.ProtoReflect.Descriptor instead.
func (*StopContainerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{5}
}

func (x *StopContainerResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type StartContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerRequest) Reset() {
	*x = StartContainerRequest{}
	mi := &file_pkg_proto_docker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerRequest) ProtoMessage() {}

func (x *StartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerRequest.ProtoReflect.Descriptor instead.
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{6}
}

func (x *StartContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StartContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerResponse) Reset() {
	*x = StartContainerResponse{}
	mi := &file_pkg_proto_docker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerResponse) ProtoMessage() {}

func (x *StartContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerResponse.ProtoReflect.Descriptor instead.
func (*StartContainerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{7}
}

func (x *StartContainerResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeleteContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerRequest) Reset() {
	*x = DeleteContainerRequest{}
	mi := &file_pkg_proto_docker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerRequest) ProtoMessage() {}

func (x *DeleteContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerRequest.ProtoReflect.Descriptor instead.
func (*DeleteContainerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type DeleteContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerResponse) Reset() {
	*x = DeleteContainerResponse{}
	mi := &file_pkg_proto_docker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerResponse) ProtoMessage() {}

func (x *DeleteContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerResponse.ProtoReflect.Descriptor instead.
func (*DeleteContainerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteContainerResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetContainerLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerLogsRequest) Reset() {
	*x = GetContainerLogsRequest{}
	mi := &file_pkg_proto_docker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerLogsRequest) ProtoMessage() {}

func (x *GetContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*GetContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{10}
}

func (x *GetContainerLogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type GetContainerLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerLogsResponse) Reset() {
	*x = GetContainerLogsResponse{}
	mi := &file_pkg_proto_docker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerLogsResponse) ProtoMessage() {}

func (x *GetContainerLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerLogsResponse.ProtoReflect.Descriptor instead.
func (*GetContainerLogsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{11}
}

func (x *GetContainerLogsResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Created       int64                  `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Names         []string               `protobuf:"bytes,7,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_pkg_proto_docker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{12}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Container) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Container) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Container) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_pkg_proto_docker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{13}
}

func (x *GetImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Dockerfile    []byte                 `protobuf:"bytes,2,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	Image         *Image                 `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageResponse) Reset() {
	*x = GetImageResponse{}
	mi := &file_pkg_proto_docker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageResponse) ProtoMessage() {}

func (x *GetImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageResponse.ProtoReflect.Descriptor instead.
func (*GetImageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{14}
}

func (x *GetImageResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetImageResponse) GetDockerfile() []byte {
	if x != nil {
		return x.Dockerfile
	}
	return nil
}

func (x *GetImageResponse) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type StoreImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreImageRequest) Reset() {
	*x = StoreImageRequest{}
	mi := &file_pkg_proto_docker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreImageRequest) ProtoMessage() {}

func (x *StoreImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreImageRequest.ProtoReflect.Descriptor instead.
func (*StoreImageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{15}
}

func (x *StoreImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreImageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type StoreImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreImageResponse) Reset() {
	*x = StoreImageResponse{}
	mi := &file_pkg_proto_docker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreImageResponse) ProtoMessage() {}

func (x *StoreImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreImageResponse.ProtoReflect.Descriptor instead.
func (*StoreImageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{16}
}

func (x *StoreImageResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type BuildImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildImageRequest) Reset() {
	*x = BuildImageRequest{}
	mi := &file_pkg_proto_docker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildImageRequest) ProtoMessage() {}

func (x *BuildImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildImageRequest.ProtoReflect.Descriptor instead.
func (*BuildImageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{17}
}

func (x *BuildImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BuildImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildImageResponse) Reset() {
	*x = BuildImageResponse{}
	mi := &file_pkg_proto_docker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildImageResponse) ProtoMessage() {}

func (x *BuildImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildImageResponse.ProtoReflect.Descriptor instead.
func (*BuildImageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{18}
}

func (x *BuildImageResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Created       int64                  `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_pkg_proto_docker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_docker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_pkg_proto_docker_proto_rawDescGZIP(), []int{19}
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Image) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Image) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

var File_pkg_proto_docker_proto protoreflect.FileDescriptor

const file_pkg_proto_docker_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/docker.proto\x12\x06docker\"*\n" +
	"\x14GetContainersRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"J\n" +
	"\x15GetContainersResponse\x121\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x11.docker.ContainerR\n" +
	"containers\"@\n" +
	"\x16CreateContainerRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\x17CreateContainerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"8\n" +
	"\x14StopContainerRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\"/\n" +
	"\x15StopContainerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"9\n" +
	"\x15StartContainerRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\"0\n" +
	"\x16StartContainerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\":\n" +
	"\x16DeleteContainerRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\"1\n" +
	"\x17DeleteContainerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\";\n" +
	"\x17GetContainerLogsRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\".\n" +
	"\x18GetContainerLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs\"\xa9\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x14\n" +
	"\x05names\x18\a \x03(\tR\x05names\"%\n" +
	"\x0fGetImageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"~\n" +
	"\x10GetImageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\x02 \x01(\fR\n" +
	"dockerfile\x12(\n" +
	"\x05image\x18\x03 \x01(\v2\r.docker.ImageH\x00R\x05image\x88\x01\x01B\b\n" +
	"\x06_image\"A\n" +
	"\x11StoreImageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\",\n" +
	"\x12StoreImageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"'\n" +
	"\x11BuildImageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x12BuildImageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"m\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated2\xd6\x05\n" +
	"\rDockerService\x12N\n" +
	"\rGetContainers\x12\x1c.docker.GetContainersRequest\x1a\x1d.docker.GetContainersResponse\"\x00\x12T\n" +
	"\x0fCreateContainer\x12\x1e.docker.CreateContainerRequest\x1a\x1f.docker.CreateContainerResponse\"\x00\x12T\n" +
	"\x0fDeleteContainer\x12\x1e.docker.DeleteContainerRequest\x1a\x1f.docker.DeleteContainerResponse\"\x00\x12W\n" +
	"\x10GetContainerLogs\x12\x1f.docker.GetContainerLogsRequest\x1a .docker.GetContainerLogsResponse\"\x00\x12Q\n" +
	"\x0eStartContainer\x12\x1d.docker.StartContainerRequest\x1a\x1e.docker.StartContainerResponse\"\x00\x12N\n" +
	"\rStopContainer\x12\x1c.docker.StopContainerRequest\x1a\x1d.docker.StopContainerResponse\"\x00\x12?\n" +
	"\bGetImage\x12\x17.docker.GetImageRequest\x1a\x18.docker.GetImageResponse\"\x00\x12E\n" +
	"\n" +
	"StoreImage\x12\x19.docker.StoreImageRequest\x1a\x1a.docker.StoreImageResponse\"\x00\x12E\n" +
	"\n" +
	"BuildImage\x12\x19.docker.BuildImageRequest\x1a\x1a.docker.BuildImageResponse\"\x00B8Z6github.com/alpha-omega-corp/cloud/app/docker/pkg/protob\x06proto3"

var (
	file_pkg_proto_docker_proto_rawDescOnce sync.Once
	file_pkg_proto_docker_proto_rawDescData []byte
)

func file_pkg_proto_docker_proto_rawDescGZIP() []byte {
	file_pkg_proto_docker_proto_rawDescOnce.Do(func() {
		file_pkg_proto_docker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_docker_proto_rawDesc), len(file_pkg_proto_docker_proto_rawDesc)))
	})
	return file_pkg_proto_docker_proto_rawDescData
}

var file_pkg_proto_docker_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_proto_docker_proto_goTypes = []any{
	(*GetContainersRequest)(nil),     // 0: docker.GetContainersRequest
	(*GetContainersResponse)(nil),    // 1: docker.GetContainersResponse
	(*CreateContainerRequest)(nil),   // 2: docker.CreateContainerRequest
	(*CreateContainerResponse)(nil),  // 3: docker.CreateContainerResponse
	(*StopContainerRequest)(nil),     // 4: docker.StopContainerRequest
	(*StopContainerResponse)(nil),    // 5: docker.StopContainerResponse
	(*StartContainerRequest)(nil),    // 6: docker.StartContainerRequest
	(*StartContainerResponse)(nil),   // 7: docker.StartContainerResponse
	(*DeleteContainerRequest)(nil),   // 8: docker.DeleteContainerRequest
	(*DeleteContainerResponse)(nil),  // 9: docker.DeleteContainerResponse
	(*GetContainerLogsRequest)(nil),  // 10: docker.GetContainerLogsRequest
	(*GetContainerLogsResponse)(nil), // 11: docker.GetContainerLogsResponse
	(*Container)(nil),                // 12: docker.Container
	(*GetImageRequest)(nil),          // 13: docker.GetImageRequest
	(*GetImageResponse)(nil),         // 14: docker.GetImageResponse
	(*StoreImageRequest)(nil),        // 15: docker.StoreImageRequest
	(*StoreImageResponse)(nil),       // 16: docker.StoreImageResponse
	(*BuildImageRequest)(nil),        // 17: docker.BuildImageRequest
	(*BuildImageResponse)(nil),       // 18: docker.BuildImageResponse
	(*Image)(nil),                    // 19: docker.Image
}
var file_pkg_proto_docker_proto_depIdxs = []int32{
	12, // 0: docker.GetContainersResponse.containers:type_name -> docker.Container
	19, // 1: docker.GetImageResponse.image:type_name -> docker.Image
	0,  // 2: docker.DockerService.GetContainers:input_type -> docker.GetContainersRequest
	2,  // 3: docker.DockerService.CreateContainer:input_type -> docker.CreateContainerRequest
	8,  // 4: docker.DockerService.DeleteContainer:input_type -> docker.DeleteContainerRequest
	10, // 5: docker.DockerService.GetContainerLogs:input_type -> docker.GetContainerLogsRequest
	6,  // 6: docker.DockerService.StartContainer:input_type -> docker.StartContainerRequest
	4,  // 7: docker.DockerService.StopContainer:input_type -> docker.StopContainerRequest
	13, // 8: docker.DockerService.GetImage:input_type -> docker.GetImageRequest
	15, // 9: docker.DockerService.StoreImage:input_type -> docker.StoreImageRequest
	17, // 10: docker.DockerService.BuildImage:input_type -> docker.BuildImageRequest
	1,  // 11: docker.DockerService.GetContainers:output_type -> docker.GetContainersResponse
	3,  // 12: docker.DockerService.CreateContainer:output_type -> docker.CreateContainerResponse
	9,  // 13: docker.DockerService.DeleteContainer:output_type -> docker.DeleteContainerResponse
	11, // 14: docker.DockerService.GetContainerLogs:output_type -> docker.GetContainerLogsResponse
	7,  // 15: docker.DockerService.StartContainer:output_type -> docker.StartContainerResponse
	5,  // 16: docker.DockerService.StopContainer:output_type -> docker.StopContainerResponse
	14, // 17: docker.DockerService.GetImage:output_type -> docker.GetImageResponse
	16, // 18: docker.DockerService.StoreImage:output_type -> docker.StoreImageResponse
	18, // 19: docker.DockerService.BuildImage:output_type -> docker.BuildImageResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_docker_proto_init() }
func file_pkg_proto_docker_proto_init() {
	if File_pkg_proto_docker_proto != nil {
		return
	}
	file_pkg_proto_docker_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_docker_proto_rawDesc), len(file_pkg_proto_docker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_docker_proto_goTypes,
		DependencyIndexes: file_pkg_proto_docker_proto_depIdxs,
		MessageInfos:      file_pkg_proto_docker_proto_msgTypes,
	}.Build()
	File_pkg_proto_docker_proto = out.File
	file_pkg_proto_docker_proto_goTypes = nil
	file_pkg_proto_docker_proto_depIdxs = nil
}
