services:
  db:
    image: postgres
    container_name: app-user-db
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=user
    volumes:
      - pgdata_cloud_user:/var/lib/postgresql/data


volumes:
  pgdata_cloud_user: