// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: pkg/proto/github.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeletePackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePackageRequest) Reset() {
	*x = DeletePackageRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePackageRequest) ProtoMessage() {}

func (x *DeletePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePackageRequest.ProtoReflect.Descriptor instead.
func (*DeletePackageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{0}
}

func (x *DeletePackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeletePackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePackageResponse) Reset() {
	*x = DeletePackageResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePackageResponse) ProtoMessage() {}

func (x *DeletePackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePackageResponse.ProtoReflect.Descriptor instead.
func (*DeletePackageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{1}
}

func (x *DeletePackageResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetSecretContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretContentRequest) Reset() {
	*x = GetSecretContentRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretContentRequest) ProtoMessage() {}

func (x *GetSecretContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretContentRequest.ProtoReflect.Descriptor instead.
func (*GetSecretContentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretContentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSecretContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretContentResponse) Reset() {
	*x = GetSecretContentResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretContentResponse) ProtoMessage() {}

func (x *GetSecretContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretContentResponse.ProtoReflect.Descriptor instead.
func (*GetSecretContentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretContentResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SyncEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEnvironmentRequest) Reset() {
	*x = SyncEnvironmentRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEnvironmentRequest) ProtoMessage() {}

func (x *SyncEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*SyncEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{4}
}

type SyncEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEnvironmentResponse) Reset() {
	*x = SyncEnvironmentResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEnvironmentResponse) ProtoMessage() {}

func (x *SyncEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*SyncEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{5}
}

func (x *SyncEnvironmentResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSecretResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecretRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSecretResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetSecretsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{10}
}

type GetSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetSecretsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{11}
}

func (x *GetSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_pkg_proto_github_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{12}
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Secret) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Secret) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Files         []*File                `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_pkg_proto_github_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{13}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type SimplePackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Sha           string                 `protobuf:"bytes,5,opt,name=sha,proto3" json:"sha,omitempty"`
	GitUrl        string                 `protobuf:"bytes,6,opt,name=gitUrl,proto3" json:"gitUrl,omitempty"`
	HtmlUrl       string                 `protobuf:"bytes,7,opt,name=htmlUrl,proto3" json:"htmlUrl,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,8,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimplePackage) Reset() {
	*x = SimplePackage{}
	mi := &file_pkg_proto_github_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimplePackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplePackage) ProtoMessage() {}

func (x *SimplePackage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplePackage.ProtoReflect.Descriptor instead.
func (*SimplePackage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{14}
}

func (x *SimplePackage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SimplePackage) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SimplePackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimplePackage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SimplePackage) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *SimplePackage) GetGitUrl() string {
	if x != nil {
		return x.GitUrl
	}
	return ""
}

func (x *SimplePackage) GetHtmlUrl() string {
	if x != nil {
		return x.HtmlUrl
	}
	return ""
}

func (x *SimplePackage) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type GitPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	HtmlUrl       string                 `protobuf:"bytes,7,opt,name=htmlUrl,proto3" json:"htmlUrl,omitempty"`
	OwnerId       int64                  `protobuf:"varint,8,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	OwnerName     string                 `protobuf:"bytes,9,opt,name=ownerName,proto3" json:"ownerName,omitempty"`
	OwnerNode     string                 `protobuf:"bytes,10,opt,name=ownerNode,proto3" json:"ownerNode,omitempty"`
	OwnerType     string                 `protobuf:"bytes,11,opt,name=ownerType,proto3" json:"ownerType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitPackage) Reset() {
	*x = GitPackage{}
	mi := &file_pkg_proto_github_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitPackage) ProtoMessage() {}

func (x *GitPackage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitPackage.ProtoReflect.Descriptor instead.
func (*GitPackage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{15}
}

func (x *GitPackage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GitPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GitPackage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GitPackage) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GitPackage) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *GitPackage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GitPackage) GetHtmlUrl() string {
	if x != nil {
		return x.HtmlUrl
	}
	return ""
}

func (x *GitPackage) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GitPackage) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *GitPackage) GetOwnerNode() string {
	if x != nil {
		return x.OwnerNode
	}
	return ""
}

func (x *GitPackage) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_pkg_proto_github_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{16}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PackageIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageIdentifier) Reset() {
	*x = PackageIdentifier{}
	mi := &file_pkg_proto_github_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageIdentifier) ProtoMessage() {}

func (x *PackageIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageIdentifier.ProtoReflect.Descriptor instead.
func (*PackageIdentifier) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{17}
}

func (x *PackageIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageIdentifier) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetPackageTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageTagsRequest) Reset() {
	*x = GetPackageTagsRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageTagsRequest) ProtoMessage() {}

func (x *GetPackageTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageTagsRequest.ProtoReflect.Descriptor instead.
func (*GetPackageTagsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{18}
}

func (x *GetPackageTagsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPackageTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageTagsResponse) Reset() {
	*x = GetPackageTagsResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageTagsResponse) ProtoMessage() {}

func (x *GetPackageTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageTagsResponse.ProtoReflect.Descriptor instead.
func (*GetPackageTagsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{19}
}

func (x *GetPackageTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PackageTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageTag) Reset() {
	*x = PackageTag{}
	mi := &file_pkg_proto_github_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageTag) ProtoMessage() {}

func (x *PackageTag) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageTag.ProtoReflect.Descriptor instead.
func (*PackageTag) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{20}
}

func (x *PackageTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageTag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type DeletePackageVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Version       *int64                 `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePackageVersionRequest) Reset() {
	*x = DeletePackageVersionRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePackageVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePackageVersionRequest) ProtoMessage() {}

func (x *DeletePackageVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePackageVersionRequest.ProtoReflect.Descriptor instead.
func (*DeletePackageVersionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{21}
}

func (x *DeletePackageVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeletePackageVersionRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DeletePackageVersionRequest) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type DeletePackageVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePackageVersionResponse) Reset() {
	*x = DeletePackageVersionResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePackageVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePackageVersionResponse) ProtoMessage() {}

func (x *DeletePackageVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePackageVersionResponse.ProtoReflect.Descriptor instead.
func (*DeletePackageVersionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{22}
}

func (x *DeletePackageVersionResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreatePackageVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePackageVersionRequest) Reset() {
	*x = CreatePackageVersionRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePackageVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackageVersionRequest) ProtoMessage() {}

func (x *CreatePackageVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackageVersionRequest.ProtoReflect.Descriptor instead.
func (*CreatePackageVersionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{23}
}

func (x *CreatePackageVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePackageVersionRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CreatePackageVersionRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CreatePackageVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePackageVersionResponse) Reset() {
	*x = CreatePackageVersionResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePackageVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackageVersionResponse) ProtoMessage() {}

func (x *CreatePackageVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackageVersionResponse.ProtoReflect.Descriptor instead.
func (*CreatePackageVersionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{24}
}

func (x *CreatePackageVersionResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetPackageFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageFileRequest) Reset() {
	*x = GetPackageFileRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageFileRequest) ProtoMessage() {}

func (x *GetPackageFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageFileRequest.ProtoReflect.Descriptor instead.
func (*GetPackageFileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{25}
}

func (x *GetPackageFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPackageFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetPackageFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageFileResponse) Reset() {
	*x = GetPackageFileResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageFileResponse) ProtoMessage() {}

func (x *GetPackageFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageFileResponse.ProtoReflect.Descriptor instead.
func (*GetPackageFileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{26}
}

func (x *GetPackageFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*PackageVersion      `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageResponse) Reset() {
	*x = GetPackageResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageResponse) ProtoMessage() {}

func (x *GetPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageResponse.ProtoReflect.Descriptor instead.
func (*GetPackageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{27}
}

func (x *GetPackageResponse) GetVersions() []*PackageVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type PackageVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoName      string                 `protobuf:"bytes,1,opt,name=repoName,proto3" json:"repoName,omitempty"`
	RepoPath      string                 `protobuf:"bytes,2,opt,name=repoPath,proto3" json:"repoPath,omitempty"`
	RepoSha       string                 `protobuf:"bytes,3,opt,name=repoSha,proto3" json:"repoSha,omitempty"`
	RepoLink      string                 `protobuf:"bytes,4,opt,name=repoLink,proto3" json:"repoLink,omitempty"`
	VersionId     *int64                 `protobuf:"varint,5,opt,name=versionId,proto3,oneof" json:"versionId,omitempty"`
	VersionSha    *string                `protobuf:"bytes,6,opt,name=versionSha,proto3,oneof" json:"versionSha,omitempty"`
	VersionLink   *string                `protobuf:"bytes,7,opt,name=versionLink,proto3,oneof" json:"versionLink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageVersion) Reset() {
	*x = PackageVersion{}
	mi := &file_pkg_proto_github_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageVersion) ProtoMessage() {}

func (x *PackageVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageVersion.ProtoReflect.Descriptor instead.
func (*PackageVersion) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{28}
}

func (x *PackageVersion) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *PackageVersion) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *PackageVersion) GetRepoSha() string {
	if x != nil {
		return x.RepoSha
	}
	return ""
}

func (x *PackageVersion) GetRepoLink() string {
	if x != nil {
		return x.RepoLink
	}
	return ""
}

func (x *PackageVersion) GetVersionId() int64 {
	if x != nil && x.VersionId != nil {
		return *x.VersionId
	}
	return 0
}

func (x *PackageVersion) GetVersionSha() string {
	if x != nil && x.VersionSha != nil {
		return *x.VersionSha
	}
	return ""
}

func (x *PackageVersion) GetVersionLink() string {
	if x != nil && x.VersionLink != nil {
		return *x.VersionLink
	}
	return ""
}

type ContainerPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerPackageRequest) Reset() {
	*x = ContainerPackageRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPackageRequest) ProtoMessage() {}

func (x *ContainerPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerPackageRequest.ProtoReflect.Descriptor instead.
func (*ContainerPackageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{29}
}

func (x *ContainerPackageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContainerPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContainerPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ContainerId   int64                  `protobuf:"varint,2,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerPackageResponse) Reset() {
	*x = ContainerPackageResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPackageResponse) ProtoMessage() {}

func (x *ContainerPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerPackageResponse.ProtoReflect.Descriptor instead.
func (*ContainerPackageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{30}
}

func (x *ContainerPackageResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ContainerPackageResponse) GetContainerId() int64 {
	if x != nil {
		return x.ContainerId
	}
	return 0
}

type PushPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	VersionSHA    string                 `protobuf:"bytes,3,opt,name=versionSHA,proto3" json:"versionSHA,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPackageRequest) Reset() {
	*x = PushPackageRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPackageRequest) ProtoMessage() {}

func (x *PushPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPackageRequest.ProtoReflect.Descriptor instead.
func (*PushPackageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{31}
}

func (x *PushPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PushPackageRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PushPackageRequest) GetVersionSHA() string {
	if x != nil {
		return x.VersionSHA
	}
	return ""
}

type PushPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPackageResponse) Reset() {
	*x = PushPackageResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPackageResponse) ProtoMessage() {}

func (x *PushPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPackageResponse.ProtoReflect.Descriptor instead.
func (*PushPackageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{32}
}

func (x *PushPackageResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreatePackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePackageRequest) Reset() {
	*x = CreatePackageRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackageRequest) ProtoMessage() {}

func (x *CreatePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackageRequest.ProtoReflect.Descriptor instead.
func (*CreatePackageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{33}
}

func (x *CreatePackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreatePackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePackageResponse) Reset() {
	*x = CreatePackageResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackageResponse) ProtoMessage() {}

func (x *CreatePackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackageResponse.ProtoReflect.Descriptor instead.
func (*CreatePackageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{34}
}

func (x *CreatePackageResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageRequest) Reset() {
	*x = GetPackageRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageRequest) ProtoMessage() {}

func (x *GetPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageRequest.ProtoReflect.Descriptor instead.
func (*GetPackageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{35}
}

func (x *GetPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackagesRequest) Reset() {
	*x = GetPackagesRequest{}
	mi := &file_pkg_proto_github_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackagesRequest) ProtoMessage() {}

func (x *GetPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackagesRequest.ProtoReflect.Descriptor instead.
func (*GetPackagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{36}
}

type GetPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*SimplePackage       `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackagesResponse) Reset() {
	*x = GetPackagesResponse{}
	mi := &file_pkg_proto_github_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackagesResponse) ProtoMessage() {}

func (x *GetPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_github_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackagesResponse.ProtoReflect.Descriptor instead.
func (*GetPackagesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_github_proto_rawDescGZIP(), []int{37}
}

func (x *GetPackagesResponse) GetPackages() []*SimplePackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_pkg_proto_github_proto protoreflect.FileDescriptor

const file_pkg_proto_github_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/github.proto\x12\x06github\"*\n" +
	"\x14DeletePackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x15DeletePackageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"-\n" +
	"\x17GetSecretContentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\x18GetSecretContentResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\x18\n" +
	"\x16SyncEnvironmentRequest\"1\n" +
	"\x17SyncEnvironmentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\")\n" +
	"\x13DeleteSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x14DeleteSecretResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"C\n" +
	"\x13CreateSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\".\n" +
	"\x14CreateSecretResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"\x13\n" +
	"\x11GetSecretsRequest\">\n" +
	"\x12GetSecretsResponse\x12(\n" +
	"\asecrets\x18\x01 \x03(\v2\x0e.github.SecretR\asecrets\"x\n" +
	"\x06Secret\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\tR\tupdatedAt\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\"A\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\x05files\x18\x02 \x03(\v2\f.github.FileR\x05files\"\xc5\x01\n" +
	"\rSimplePackage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x10\n" +
	"\x03sha\x18\x05 \x01(\tR\x03sha\x12\x16\n" +
	"\x06gitUrl\x18\x06 \x01(\tR\x06gitUrl\x12\x18\n" +
	"\ahtmlUrl\x18\a \x01(\tR\ahtmlUrl\x12 \n" +
	"\vdownloadUrl\x18\b \x01(\tR\vdownloadUrl\"\x9e\x02\n" +
	"\n" +
	"GitPackage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x18\n" +
	"\ahtmlUrl\x18\a \x01(\tR\ahtmlUrl\x12\x18\n" +
	"\aownerId\x18\b \x01(\x03R\aownerId\x12\x1c\n" +
	"\townerName\x18\t \x01(\tR\townerName\x12\x1c\n" +
	"\townerNode\x18\n" +
	" \x01(\tR\townerNode\x12\x1c\n" +
	"\townerType\x18\v \x01(\tR\townerType\"4\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"9\n" +
	"\x11PackageIdentifier\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"+\n" +
	"\x15GetPackageTagsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16GetPackageTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"2\n" +
	"\n" +
	"PackageTag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"n\n" +
	"\x1bDeletePackageVersionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x03H\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"6\n" +
	"\x1cDeletePackageVersionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"]\n" +
	"\x1bCreatePackageVersionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"6\n" +
	"\x1cCreatePackageVersionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"?\n" +
	"\x15GetPackageFileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"2\n" +
	"\x16GetPackageFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"H\n" +
	"\x12GetPackageResponse\x122\n" +
	"\bversions\x18\x01 \x03(\v2\x16.github.PackageVersionR\bversions\"\x9a\x02\n" +
	"\x0ePackageVersion\x12\x1a\n" +
	"\brepoName\x18\x01 \x01(\tR\brepoName\x12\x1a\n" +
	"\brepoPath\x18\x02 \x01(\tR\brepoPath\x12\x18\n" +
	"\arepoSha\x18\x03 \x01(\tR\arepoSha\x12\x1a\n" +
	"\brepoLink\x18\x04 \x01(\tR\brepoLink\x12!\n" +
	"\tversionId\x18\x05 \x01(\x03H\x00R\tversionId\x88\x01\x01\x12#\n" +
	"\n" +
	"versionSha\x18\x06 \x01(\tH\x01R\n" +
	"versionSha\x88\x01\x01\x12%\n" +
	"\vversionLink\x18\a \x01(\tH\x02R\vversionLink\x88\x01\x01B\f\n" +
	"\n" +
	"_versionIdB\r\n" +
	"\v_versionShaB\x0e\n" +
	"\f_versionLink\"=\n" +
	"\x17ContainerPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"T\n" +
	"\x18ContainerPackageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12 \n" +
	"\vcontainerId\x18\x02 \x01(\x03R\vcontainerId\"Z\n" +
	"\x12PushPackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x1e\n" +
	"\n" +
	"versionSHA\x18\x03 \x01(\tR\n" +
	"versionSHA\"-\n" +
	"\x13PushPackageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"*\n" +
	"\x14CreatePackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x15CreatePackageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"'\n" +
	"\x11GetPackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12GetPackagesRequest\"H\n" +
	"\x13GetPackagesResponse\x121\n" +
	"\bpackages\x18\x01 \x03(\v2\x15.github.SimplePackageR\bpackages2\xe3\t\n" +
	"\rGithubService\x12W\n" +
	"\x10GetSecretContent\x12\x1f.github.GetSecretContentRequest\x1a .github.GetSecretContentResponse\"\x00\x12E\n" +
	"\n" +
	"GetSecrets\x12\x19.github.GetSecretsRequest\x1a\x1a.github.GetSecretsResponse\"\x00\x12K\n" +
	"\fCreateSecret\x12\x1b.github.CreateSecretRequest\x1a\x1c.github.CreateSecretResponse\"\x00\x12K\n" +
	"\fDeleteSecret\x12\x1b.github.DeleteSecretRequest\x1a\x1c.github.DeleteSecretResponse\"\x00\x12T\n" +
	"\x0fSyncEnvironment\x12\x1e.github.SyncEnvironmentRequest\x1a\x1f.github.SyncEnvironmentResponse\"\x00\x12H\n" +
	"\vPushPackage\x12\x1a.github.PushPackageRequest\x1a\x1b.github.PushPackageResponse\"\x00\x12W\n" +
	"\x10ContainerPackage\x12\x1f.github.ContainerPackageRequest\x1a .github.ContainerPackageResponse\"\x00\x12H\n" +
	"\vGetPackages\x12\x1a.github.GetPackagesRequest\x1a\x1b.github.GetPackagesResponse\"\x00\x12E\n" +
	"\n" +
	"GetPackage\x12\x19.github.GetPackageRequest\x1a\x1a.github.GetPackageResponse\"\x00\x12Q\n" +
	"\x0eGetPackageTags\x12\x1d.github.GetPackageTagsRequest\x1a\x1e.github.GetPackageTagsResponse\"\x00\x12Q\n" +
	"\x0eGetPackageFile\x12\x1d.github.GetPackageFileRequest\x1a\x1e.github.GetPackageFileResponse\"\x00\x12N\n" +
	"\rCreatePackage\x12\x1c.github.CreatePackageRequest\x1a\x1d.github.CreatePackageResponse\"\x00\x12N\n" +
	"\rDeletePackage\x12\x1c.github.DeletePackageRequest\x1a\x1d.github.DeletePackageResponse\"\x00\x12c\n" +
	"\x14CreatePackageVersion\x12#.github.CreatePackageVersionRequest\x1a$.github.CreatePackageVersionResponse\"\x00\x12c\n" +
	"\x14DeletePackageVersion\x12#.github.DeletePackageVersionRequest\x1a$.github.DeletePackageVersionResponse\"\x00B8Z6github.com/alpha-omega-corp/cloud/app/github/pkg/protob\x06proto3"

var (
	file_pkg_proto_github_proto_rawDescOnce sync.Once
	file_pkg_proto_github_proto_rawDescData []byte
)

func file_pkg_proto_github_proto_rawDescGZIP() []byte {
	file_pkg_proto_github_proto_rawDescOnce.Do(func() {
		file_pkg_proto_github_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_github_proto_rawDesc), len(file_pkg_proto_github_proto_rawDesc)))
	})
	return file_pkg_proto_github_proto_rawDescData
}

var file_pkg_proto_github_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_pkg_proto_github_proto_goTypes = []any{
	(*DeletePackageRequest)(nil),         // 0: github.DeletePackageRequest
	(*DeletePackageResponse)(nil),        // 1: github.DeletePackageResponse
	(*GetSecretContentRequest)(nil),      // 2: github.GetSecretContentRequest
	(*GetSecretContentResponse)(nil),     // 3: github.GetSecretContentResponse
	(*SyncEnvironmentRequest)(nil),       // 4: github.SyncEnvironmentRequest
	(*SyncEnvironmentResponse)(nil),      // 5: github.SyncEnvironmentResponse
	(*DeleteSecretRequest)(nil),          // 6: github.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),         // 7: github.DeleteSecretResponse
	(*CreateSecretRequest)(nil),          // 8: github.CreateSecretRequest
	(*CreateSecretResponse)(nil),         // 9: github.CreateSecretResponse
	(*GetSecretsRequest)(nil),            // 10: github.GetSecretsRequest
	(*GetSecretsResponse)(nil),           // 11: github.GetSecretsResponse
	(*Secret)(nil),                       // 12: github.Secret
	(*Package)(nil),                      // 13: github.Package
	(*SimplePackage)(nil),                // 14: github.SimplePackage
	(*GitPackage)(nil),                   // 15: github.GitPackage
	(*File)(nil),                         // 16: github.File
	(*PackageIdentifier)(nil),            // 17: github.PackageIdentifier
	(*GetPackageTagsRequest)(nil),        // 18: github.GetPackageTagsRequest
	(*GetPackageTagsResponse)(nil),       // 19: github.GetPackageTagsResponse
	(*PackageTag)(nil),                   // 20: github.PackageTag
	(*DeletePackageVersionRequest)(nil),  // 21: github.DeletePackageVersionRequest
	(*DeletePackageVersionResponse)(nil), // 22: github.DeletePackageVersionResponse
	(*CreatePackageVersionRequest)(nil),  // 23: github.CreatePackageVersionRequest
	(*CreatePackageVersionResponse)(nil), // 24: github.CreatePackageVersionResponse
	(*GetPackageFileRequest)(nil),        // 25: github.GetPackageFileRequest
	(*GetPackageFileResponse)(nil),       // 26: github.GetPackageFileResponse
	(*GetPackageResponse)(nil),           // 27: github.GetPackageResponse
	(*PackageVersion)(nil),               // 28: github.PackageVersion
	(*ContainerPackageRequest)(nil),      // 29: github.ContainerPackageRequest
	(*ContainerPackageResponse)(nil),     // 30: github.ContainerPackageResponse
	(*PushPackageRequest)(nil),           // 31: github.PushPackageRequest
	(*PushPackageResponse)(nil),          // 32: github.PushPackageResponse
	(*CreatePackageRequest)(nil),         // 33: github.CreatePackageRequest
	(*CreatePackageResponse)(nil),        // 34: github.CreatePackageResponse
	(*GetPackageRequest)(nil),            // 35: github.GetPackageRequest
	(*GetPackagesRequest)(nil),           // 36: github.GetPackagesRequest
	(*GetPackagesResponse)(nil),          // 37: github.GetPackagesResponse
}
var file_pkg_proto_github_proto_depIdxs = []int32{
	12, // 0: github.GetSecretsResponse.secrets:type_name -> github.Secret
	16, // 1: github.Package.files:type_name -> github.File
	28, // 2: github.GetPackageResponse.versions:type_name -> github.PackageVersion
	14, // 3: github.GetPackagesResponse.packages:type_name -> github.SimplePackage
	2,  // 4: github.GithubService.GetSecretContent:input_type -> github.GetSecretContentRequest
	10, // 5: github.GithubService.GetSecrets:input_type -> github.GetSecretsRequest
	8,  // 6: github.GithubService.CreateSecret:input_type -> github.CreateSecretRequest
	6,  // 7: github.GithubService.DeleteSecret:input_type -> github.DeleteSecretRequest
	4,  // 8: github.GithubService.SyncEnvironment:input_type -> github.SyncEnvironmentRequest
	31, // 9: github.GithubService.PushPackage:input_type -> github.PushPackageRequest
	29, // 10: github.GithubService.ContainerPackage:input_type -> github.ContainerPackageRequest
	36, // 11: github.GithubService.GetPackages:input_type -> github.GetPackagesRequest
	35, // 12: github.GithubService.GetPackage:input_type -> github.GetPackageRequest
	18, // 13: github.GithubService.GetPackageTags:input_type -> github.GetPackageTagsRequest
	25, // 14: github.GithubService.GetPackageFile:input_type -> github.GetPackageFileRequest
	33, // 15: github.GithubService.CreatePackage:input_type -> github.CreatePackageRequest
	0,  // 16: github.GithubService.DeletePackage:input_type -> github.DeletePackageRequest
	23, // 17: github.GithubService.CreatePackageVersion:input_type -> github.CreatePackageVersionRequest
	21, // 18: github.GithubService.DeletePackageVersion:input_type -> github.DeletePackageVersionRequest
	3,  // 19: github.GithubService.GetSecretContent:output_type -> github.GetSecretContentResponse
	11, // 20: github.GithubService.GetSecrets:output_type -> github.GetSecretsResponse
	9,  // 21: github.GithubService.CreateSecret:output_type -> github.CreateSecretResponse
	7,  // 22: github.GithubService.DeleteSecret:output_type -> github.DeleteSecretResponse
	5,  // 23: github.GithubService.SyncEnvironment:output_type -> github.SyncEnvironmentResponse
	32, // 24: github.GithubService.PushPackage:output_type -> github.PushPackageResponse
	30, // 25: github.GithubService.ContainerPackage:output_type -> github.ContainerPackageResponse
	37, // 26: github.GithubService.GetPackages:output_type -> github.GetPackagesResponse
	27, // 27: github.GithubService.GetPackage:output_type -> github.GetPackageResponse
	19, // 28: github.GithubService.GetPackageTags:output_type -> github.GetPackageTagsResponse
	26, // 29: github.GithubService.GetPackageFile:output_type -> github.GetPackageFileResponse
	34, // 30: github.GithubService.CreatePackage:output_type -> github.CreatePackageResponse
	1,  // 31: github.GithubService.DeletePackage:output_type -> github.DeletePackageResponse
	24, // 32: github.GithubService.CreatePackageVersion:output_type -> github.CreatePackageVersionResponse
	22, // 33: github.GithubService.DeletePackageVersion:output_type -> github.DeletePackageVersionResponse
	19, // [19:34] is the sub-list for method output_type
	4,  // [4:19] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_github_proto_init() }
func file_pkg_proto_github_proto_init() {
	if File_pkg_proto_github_proto != nil {
		return
	}
	file_pkg_proto_github_proto_msgTypes[21].OneofWrappers = []any{}
	file_pkg_proto_github_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_github_proto_rawDesc), len(file_pkg_proto_github_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_github_proto_goTypes,
		DependencyIndexes: file_pkg_proto_github_proto_depIdxs,
		MessageInfos:      file_pkg_proto_github_proto_msgTypes,
	}.Build()
	File_pkg_proto_github_proto = out.File
	file_pkg_proto_github_proto_goTypes = nil
	file_pkg_proto_github_proto_depIdxs = nil
}
